#цитата из  Томаса Уотсона.  который  в  1943  г.  был  директором  IBM 
quote  ="Думаю.  на  мировом рынке можно будет  продать штук пять  компьютеров." 
рrint("Исходная  цитата : ") 
print(quote) 
print("\nOнa же  в  верхнем регистре:") 
print(quote.upper()) 
print("\nB  нижнем регистре:") 
print(quote.lower()) 
print("\nKaк заголовок:") 
pr;nt(quote.title()) 
print("\nC  ма-а-аленькой  заменой:") 
print(quote.replace("штyк пять".  "несколько миллионов")) 
print("\nA  вот опять  исходная цитата:") 
print(quote) 
input("\n\nHaжмитe Enter.  чтобы выйти.")